name: crosswords
adopt-info: crosswords
grade: stable
confinement: strict
base: core24
contact: https://github.com/phqen1x/crosswords-snap/issues
issues: https://github.com/phqen1x/crosswords-snap/issues
website: https://gitlab.gnome.org/jrb/crosswords
license: GPL-3.0+
icon: icon512.png
platforms:
  amd64:
  arm64:

slots:
  # for GtkApplication registration
  crosswords:
    interface: dbus
    bus: session
    name: org.gnome.Crosswords
  crossword-editor:
    interface: dbus
    bus: session
    name: org.gnome.Crosswords.Editor

apps:
  crosswords:
    extensions: [gnome]
    command: usr/bin/crosswords
    desktop: usr/share/applications/org.gnome.Crosswords.desktop
    common-id: org.gnome.Crosswords
  editor:
    extensions: [gnome]
    command: usr/bin/crossword-editor
    desktop: usr/share/applications/org.gnome.Crosswords.Editor.desktop

parts:
  libipuz:
    source: https://gitlab.gnome.org/jrb/libipuz.git
    source-type: git
    source-tag: 0.5.2 #libipuz
    plugin: meson
    meson-parameters: [--prefix=/usr, -Ddocumentation=disabled]
    build-packages:
      - cargo-1.81
    build-environment:
      - PATH: /usr/lib/rust-1.81/bin:$PATH
    prime:
      - usr/lib/*/liblibipuz*so*
      - usr/lib/*/girepository-1.0

  crosswords:
    after: [libipuz]
    source: https://gitlab.gnome.org/jrb/crosswords.git
    source-type: git
    source-tag: 0.3.15 #crosswords
    plugin: meson
    meson-parameters: [--prefix=/usr, -Ddevelopment=false]
    parse-info: [usr/share/metainfo/org.gnome.Crosswords.metainfo.xml]
    build-packages: 
      - cargo-1.81
      - python3-jinja2
      - python3-markdown
      - python3-markupsafe
      - python3-pygments
      - python3-typogrify
    build-environment:
      - PATH: /usr/lib/rust-1.81/bin:$PATH
    stage-packages:
      - python3-jinja2
      - python3-markdown
      - python3-markupsafe
      - python3-pygments
      - python3-typogrify
